version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "alembic upgrade head
             uvicorn main:app --reload --host 0.0.0.0 --port 8000"

    env_file:
      - .env
    depends_on:
      - db
    image: fastapi-city-temperature-management:0.3

  db:
    image: sqlalchemy/mysql:5.7
