"""Description of the migration

Revision ID: 1a83e1195d0d
Revises: 33c61a9e9ae0
Create Date: 2023-07-27 14:46:31.640028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a83e1195d0d'
down_revision = '33c61a9e9ae0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
