"""initial migration

Revision ID: 2166113385d7
Revises: 9e6d0ca7f80a
Create Date: 2023-08-29 10:09:04.147479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2166113385d7'
down_revision: Union[str, None] = '9e6d0ca7f80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    # ### end Alembic commands ###
