"""Initial migration

Revision ID: 287ad451141a
Revises: 2166113385d7
Create Date: 2023-08-29 15:18:16.749208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287ad451141a'
down_revision: Union[str, None] = '2166113385d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cities_name', table_name='cities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cities_name', 'cities', ['name'], unique=False)
    # ### end Alembic commands ###
