"""Initial migration

Revision ID: 33c61a9e9ae0
Revises: 62f59a12060b
Create Date: 2023-07-27 14:46:11.301726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c61a9e9ae0'
down_revision = '62f59a12060b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
