"""Upgrade migration

Revision ID: 4d104d9553b1
Revises: 1ab50d72fb3f
Create Date: 2023-08-03 20:33:24.896581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d104d9553b1'
down_revision = '1ab50d72fb3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('additional_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'additional_info')
    # ### end Alembic commands ###
