"""Initial migration

Revision ID: 7e71c6a99ef0
Revises: 7d215d0f8d41
Create Date: 2023-08-28 13:33:19.365318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e71c6a99ef0'
down_revision: Union[str, None] = '7d215d0f8d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
