"""Initial migration

Revision ID: 8c1b8e9da1e2
Revises: 1bce705c6dcc
Create Date: 2023-08-14 19:01:29.157617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1b8e9da1e2'
down_revision: Union[str, None] = '1bce705c6dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
