"""empty message

Revision ID: 8f9f185d737c
Revises: bb4d934a6012
Create Date: 2023-08-28 18:17:58.695079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9f185d737c'
down_revision: Union[str, None] = 'bb4d934a6012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperature', 'temperature')
    # ### end Alembic commands ###
