"""Initial migration

Revision ID: 930473829e59
Revises: 
Create Date: 2023-08-03 11:48:24.036014

"""

# revision identifiers, used by Alembic.
revision = '930473829e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
