"""added unique to City.name

Revision ID: 9c673ce3d89a
Revises: 6352d464ef08
Create Date: 2023-08-24 13:58:25.536435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c673ce3d89a'
down_revision: Union[str, None] = '6352d464ef08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cities_name', table_name='cities')
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.create_index('ix_cities_name', 'cities', ['name'], unique=False)
    # ### end Alembic commands ###
