"""Initial migration_01

Revision ID: 9d333384bdb7
Revises: f71e16d3d0ef
Create Date: 2023-09-02 18:50:19.566991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d333384bdb7'
down_revision = 'f71e16d3d0ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
