"""description_of_changes

Revision ID: eac76ea4f9f6
Revises: 1a83e1195d0d
Create Date: 2023-07-27 16:35:16.970613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac76ea4f9f6'
down_revision = '1a83e1195d0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
