"""Make City.additional_info 'Text' type

Revision ID: f176a736e0f0
Revises: f02d85bdf0f0
Create Date: 2024-03-05 21:20:03.627307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f176a736e0f0'
down_revision: Union[str, None] = 'f02d85bdf0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'additional_info',
               existing_type=sa.VARCHAR(length=511),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'additional_info',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=511),
               existing_nullable=True)
    # ### end Alembic commands ###
