"""Add additional_info to City

Revision ID: f8a514f075c8
Revises: 0dc38d65c1dd
Create Date: 2024-03-05 21:24:39.583334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a514f075c8'
down_revision: Union[str, None] = '0dc38d65c1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'additional_info')
    # ### end Alembic commands ###
